//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorConsultasMedicas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GerenciadorConsultasMedicasEntities : DbContext
    {
        public GerenciadorConsultasMedicasEntities()
            : base("name=GerenciadorConsultasMedicasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConsultaMedica> ConsultaMedica { get; set; }
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<Medicos> Medicos { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
    
        public virtual ObjectResult<ListarConsultasOrdenadasPorDataEHora_Result> ListarConsultasOrdenadasPorDataEHora()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarConsultasOrdenadasPorDataEHora_Result>("ListarConsultasOrdenadasPorDataEHora");
        }
    
        public virtual ObjectResult<ListarConsultasPorMedico_Result> ListarConsultasPorMedico(string nomeMedico, string sobrenomeMedico)
        {
            var nomeMedicoParameter = nomeMedico != null ?
                new ObjectParameter("NomeMedico", nomeMedico) :
                new ObjectParameter("NomeMedico", typeof(string));
    
            var sobrenomeMedicoParameter = sobrenomeMedico != null ?
                new ObjectParameter("SobrenomeMedico", sobrenomeMedico) :
                new ObjectParameter("SobrenomeMedico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarConsultasPorMedico_Result>("ListarConsultasPorMedico", nomeMedicoParameter, sobrenomeMedicoParameter);
        }
    
        public virtual ObjectResult<ListarConsultasOrdenadasPorDataEHora1_Result1> ListarConsultasOrdenadasPorDataEHora1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarConsultasOrdenadasPorDataEHora1_Result1>("ListarConsultasOrdenadasPorDataEHora1");
        }
    }
}
