//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorConsultasMedicas.Models
{
    using System;
    
    public partial class ListarConsultasOrdenadasPorDataEHora1_Result1
    {
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> Horario { get; set; }
        public string Medico { get; set; }
        public string Paciente { get; set; }
    }
}
